# Generated by Django 4.0.5 on 2022-06-09 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('task', models.CharField(max_length=50)),
                ('inloc', models.CharField(max_length=120)),
                ('outloc', models.CharField(max_length=120)),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='start time')),
                ('duration', models.FloatField()),
                ('inloc_size', models.IntegerField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('time_in', models.DateTimeField(auto_now_add=True, verbose_name='time in')),
                ('time_out', models.DateTimeField(auto_now=True, verbose_name='time out')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
