# Generated by Django 3.2.7 on 2022-06-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_document_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='folder',
            field=models.FileField(blank=True, null=True, upload_to='documents/uploaded/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/uploaded/%Y/%m/%d/'),
        ),
    ]
