# Generated by Django 3.2.7 on 2022-07-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0007_auto_20220630_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='convert',
            name='converted_document',
            field=models.FileField(blank=True, null=True, upload_to=None),
        ),
    ]
