# Generated by Django 3.2.7 on 2022-07-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0008_convert_converted_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocr',
            name='ocred_document',
            field=models.FileField(blank=True, null=True, upload_to=None),
        ),
    ]
