"""Initial db migration

Revision ID: d065d20dc593
Revises: 
Create Date: 2021-08-31 00:29:41.435281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd065d20dc593'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('dataset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('brief_description', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_name'), 'dataset', ['name'], unique=False)
    op.create_table('conversion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversion_name', sa.String(length=120), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('from_type', sa.String(length=25), nullable=True),
    sa.Column('to_type', sa.String(length=25), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dataset_meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_type', sa.String(length=120), nullable=True),
    sa.Column('dataset_size', sa.Integer(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('dataset_filename', sa.String(length=120), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dataset_meta')
    op.drop_table('conversion')
    op.drop_index(op.f('ix_dataset_name'), table_name='dataset')
    op.drop_table('dataset')
    op.drop_table('user')
    # ### end Alembic commands ###
